### ISSUE TITLE
Import and Run in Android Studio 

### ISSUE THREAD

**Issue by NeilHendrick** [mapbox/store-locator-android#12]
I've imported the project into Android Studio  (Android Studio 3.1 Canary 5), but I can't get the project to Run. 
I get the error:  "Error running store-locator-android-master []: No task to execute is specified"

Not sure how to proceed, please advise. Thank-you.

**Comment by langsmith** [comment]
Hey @NeilHendrick , apologies for responding to this so late. Try building and running the project again? Does it work for you?

**Comment by langsmith** [comment]
Conversation is stagnant. Happy to re-open if conversation picks back up

**Comment by kiwenoob** [comment]
Hi @langsmith , happy to re-open the conversation :D 
I have a similar issue, project can't run because Android Studio (3.5.3) can't find the module.
How can I tackle that please?

Thanks very much
