### ISSUE TITLE
App crash with error "terminating with uncaught exception of type jni::PendingJavaException" in logcat

### ISSUE THREAD

**Issue by mayank90807** [mapbox/store-locator-android#15]
Logcat errors:
02-16 13:47:48.904 30891-30891/com.mapbox.storefinder E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException
02-16 13:47:48.904 30891-30891/com.mapbox.storefinder A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 30891 (box.storefinder)

**Comment by langsmith** [comment]
Hey @mayank90807 , thanks very much for your interest in this project. Is this a problem that you're still experiencing?

**Comment by mayank90807** [comment]
Yes...I am still experiencing it!

**Comment by langsmith** [comment]
Conversation stagnant. Happy to re-open this if things progress.

**Comment by imkarthi24** [comment]
Hi!I'm still facing that issue,even with the latest release

**Comment by epankou** [comment]
same issue for me

**Comment by langsmith** [comment]
@imkarthi24 @epankou , when is this crash happening? Have you adjusted the code in any way?

**Comment by panashka** [comment]
@langsmith I am following this tutorial https://docs.mapbox.com/help/tutorials/android-navigation-sdk/
The crash happens when I press the button "start navigation".
Here is my build.gradle:

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.0"
    defaultConfig {
        applicationId "com.example.myapplication"
        minSdkVersion 26
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    mavenCentral()
    maven { url 'https://mapbox.bintray.com/mapbox' }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.41.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
`

**Comment by langsmith** [comment]
Hi @panashka . https://docs.mapbox.com/help/tutorials/android-navigation-sdk is different than the https://github.com/mapbox/store-locator-android app. Please contact Mapbox Support via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 if you're having issues implementing Mapbox.

**Comment by Aimness** [comment]
Hi. I have the same problem: 
E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 20545 (OnlineFileSourc), pid 20405 (d.myapplication)
I am following [this](https://docs.mapbox.com/android/java/examples/generate-an-optimized-route/)  tutorial and I did everything exactly the same as there.
Here is what i have in my build.gradle:
 implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.1')
            { transitive=true }
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:5.8.0'
    implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6')
            {
                exclude group: 'android.arch.core'
                transitive = true
            }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.11.0'

Also, after adding Mapbox to my project i have a prolem with Picasso
