### ISSUE TITLE
2 modules cannot be loaded

### ISSUE THREAD

**Issue by manishnewprojects** [mapbox/store-locator-android#16]
Get this error right away -??

 
![screen shot 2018-03-17 at 10 17 12 am](https://user-images.githubusercontent.com/27633226/37558129-876d9cc0-29cc-11e8-9a16-bf592acf4d51.png)
)

**Comment by langsmith** [comment]
Thanks for the heads up @manishnewprojects .  I will look into this. I don't _think_ this should be an issue for you being able to open and build the store locator though. Please let me know if it's causing problems for you.

**Comment by ali151yek** [comment]
same probleme ! ,
I tried to remove the slected and run the app 
it closes ,  when I select a theme .

**Comment by langsmith** [comment]
Closing because stale. Happy to keep looking into this if it's an issue for OP or anyone else.
