### ISSUE TITLE
cannot find symbol convert distance

### ISSUE THREAD

**Issue by tech106** [mapbox/store-locator-android#17]
![image](https://user-images.githubusercontent.com/13192177/37567863-f8b84fba-2b07-11e8-9746-6620f825bdae.png)

**Comment by akshay24s** [comment]
Same error Cannot find convertDistance function

**Comment by langsmith** [comment]
Sorry 'bout that. That method from our Mapbox Java SDK was changed to `convertLength` and this project was playing catch up

Fixed this error in this commit https://github.com/mapbox/store-locator-android/commit/8b247889f86a9385e45cddd12c487b364e33c117

If you all are still having issues, please let me know.
