### ISSUE TITLE
Cant use my location.

### ISSUE THREAD

**Issue by Blanksite** [mapbox/store-locator-android#22]
Hi i want make this in my location but always error. 
here my code
```
  private static final LatLngBounds LOCKED_MAP_CAMERA_BOUNDS = new LatLngBounds.Builder()
    .include(new LatLng(106.96861, -6.25556))
    .include(new LatLng(107.0136,
      -6.2308)).build();
  //simulated user location
  private static final LatLng MOCK_DEVICE_LOCATION_LAT_LNG = new LatLng(106, -6);
```

and the error log is 
  Caused by: java.lang.IllegalArgumentException: latitude must be between -90 and 90

**Comment by langsmith** [comment]
Your lat/lng coordinates are reversed. They're invalid. I tried swapping them and it looks like you're trying to set a boundary in Indonesia, correct?

Try  `-6.25556,106.96861` and  `-6.2308,107.0136` instead. Use `-6,106` for the mock device location. So it'd look like: 

```
private static final LatLngBounds LOCKED_MAP_CAMERA_BOUNDS = new LatLngBounds.Builder()
    .include(new LatLng(-6.25556, 106.96861))
    .include(new LatLng(-6.2308, 107.0136)).build();
  //simulated user location
  private static final LatLng MOCK_DEVICE_LOCATION_LAT_LNG = new LatLng(-6, 106);
```

**Comment by langsmith** [comment]
@Blanksite  , forgot to say "Thanks for using Mapbox!" 😃
