### ISSUE TITLE
geojson url

### ISSUE THREAD

**Issue by physetyo** [mapbox/store-locator-android#23]
how to get geojson from url?

**Comment by langsmith** [comment]
Hi @physetyo . Thanks for looking into this project. 

It kind of depends on where the data lives.

You can retrieve features from a Mapbox Dataset in your Mapbox Studio account:

```
try{

loadedMapStyle.addSource(new GeoJsonSource("source-id", new URL( "https://api.mapbox.com/datasets/v1/{YOUR_MAPBOX_USERNAME_HERE}/{DATASET_ID_HERE}/features?access_token=" + getString(R.string.mapbox_access_token))

} catch (MalformedURLException exception) {
      Log.d(TAG, "MalformedURLException exception = " + exception);
}
```


https://docs.mapbox.com/studio-manual/reference/datasets/



```

 try {
              URL geoJsonUrl = new URL("https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_50m_urban_areas.geojson");
              GeoJsonSource source = new GeoJsonSource("source-id", geoJsonUrl);
              mapboxMap.getStyle().addSource(source);

            } catch (MalformedURLException malformedUrlException) {
              malformedUrlException.printStackTrace();
            }
```

The examples in https://github.com/mapbox/mapbox-android-demo use a `GeoJsonSource` in many different ways. You can reference that project to see the different ways of retrieving GeoJSON data from an external URL.
