### ISSUE TITLE
Application black screen after choosing theme.

### ISSUE THREAD

**Issue by johnnymesibas13** [mapbox/store-locator-android#25]
Hello. I have cloned the store locator and open it on my android studio (3.3.2). After loading in android studio, it gives an error saying, "2 modules cannot be loaded" which is the StoreLocator.iml and app.iml respectively. I didn't mind those errors though and still run the app. Now, the app installed successfully on my device but the problem is that after choosing my preferred theme the screen goes black. I will attach here a gif. , 
![storelocator](https://user-images.githubusercontent.com/38825506/56076183-6809e280-5e00-11e9-83a5-4b0b96ce70cc.gif)

**Comment by langsmith** [comment]
Hey @johnnymesibas13 , thanks for checking out this project. 

- Have you correctly pasted your Mapbox access token into the string resource file? https://github.com/mapbox/store-locator-android/blob/master/StoreLocator/app/src/main/res/values/strings.xml#L3

- Are you getting an error/crash in the log cat, when the screen turns black?

**Comment by langsmith** [comment]
Also, what device are you using?

**Comment by johnnymesibas13** [comment]
Hello, @langsmith. Thanks for your response. I have correctly pasted my Mapbox access token in the dev-config.xml file but still, the problem exists. 

So far, I am only getting an error:
`2019-04-20 11:14:48.979 20294-20294/com.mapbox.storefinder E/RecyclerView: No adapter attached; skipping layout
2019-04-20 11:14:50.258 20294-20580/com.mapbox.storefinder D/Mbgl-HttpRequest: [HTTP] Request with response = 401: Unauthorized
2019-04-20 11:14:50.262 20294-20294/com.mapbox.storefinder E/Mbgl: {box.storefinder}[Setup]: loading style failed: HTTP status code 401`

And my device is Oppo A3s

**Comment by johnnymesibas13** [comment]
I will attach here the picture of the error.

![Capture](https://user-images.githubusercontent.com/38825506/56451520-b2d6ad80-635e-11e9-9044-6d5aff6ba3ec.PNG)

**Comment by langsmith** [comment]
Any code that you can share? Have you made any changes to `MapActivity` ? To `CustomThemeManager` class? Code changes elsewhere?

**Comment by johnnymesibas13** [comment]
The only code I changed is the access token and nothing else. Then I used the application as is.

**Comment by RCK-DEV** [comment]
> Hello, @langsmith. Thanks for your response. I have correctly pasted my Mapbox access token in the dev-config.xml file but still, the problem exists.
> 
> So far, I am only getting an error:
> `2019-04-20 11:14:48.979 20294-20294/com.mapbox.storefinder E/RecyclerView: No adapter attached; skipping layout 2019-04-20 11:14:50.258 20294-20580/com.mapbox.storefinder D/Mbgl-HttpRequest: [HTTP] Request with response = 401: Unauthorized 2019-04-20 11:14:50.262 20294-20294/com.mapbox.storefinder E/Mbgl: {box.storefinder}[Setup]: loading style failed: HTTP status code 401`
> 
> And my device is Oppo A3s

I have the same error message. but all the activities launches just fine in the Emulator and on a physical device (Samsung S9).

Based on your error message screenshot i'm guessing you have no internet connection or your API Key is invalid. See last two lines which indicate a HTTP Request error.

You might try updating Android studio to 3.4 and see if that works. I'm using 3.4 atm.

**Comment by langsmith** [comment]
Thanks for the comments, @RCK-DEV . Everything's working for me on my `OnePlus5` as well. 

@johnnymesibas13 , nothing in your logcat screenshot indicates that the map wouldn't even load. Do you see the word `Mapbox` when you select a theme in the app? I ask because there's a difference the `MapView` not loading and the particular style's tiles not appearing _in_ the `MapView`.

**Comment by johnnymesibas13** [comment]
@langsmith @RCK-DEV thank you sirs. i have figured it out what's the problem and it's because of the wrong token I input. Sorry for the late reply also. God Bless!

**Comment by langsmith** [comment]
Glad to hear it @johnnymesibas13 !
