### ISSUE TITLE
how i can import json from list location

### ISSUE THREAD

**Issue by iman100** [mapbox/store-locator-android#28]
hi can show point,s on map just without infowindow how i can show points with info window or like  project(store-locator) on android 
[here my app](http://s9.picofile.com/file/8361073500/Screenshot_1558243218.png)

**Comment by langsmith** [comment]
Hi @iman100 , thanks for using Mapbox.

http://s9.picofile.com/file/8361073500/Screenshot_1558243218.png is a dead link for me.



Here's how to do a simple `SymbolLayer` icon with an infowindow: https://docs.mapbox.com/android/maps/examples/symbol-layer-info-window/


If you _only_ want icons at specific points as seen in the screenshot below, then see the code at  https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/BasicSymbolLayerActivity.java

<img width="268" alt="Screen Shot 2019-05-21 at 1 26 16 PM" src="https://user-images.githubusercontent.com/4394910/58128272-0e998e00-7bcc-11e9-8f7c-a0ae48608bf6.png">

**Comment by langsmith** [comment]
Also, you can create a FeatureCollection from JSON via `FeatureCollection.fromJson()`. 

```java
          GeoJsonSource geoJsonSource = new GeoJsonSource("source-id", FeatureCollection.fromJson());
```
