### ISSUE TITLE
How to put the destinations in the order of distance??

### ISSUE THREAD

**Issue by iman100** [mapbox/store-locator-android#30]
How do I get the points I received in this example in the order of distance from someone

**Comment by langsmith** [comment]
hey @iman100 , you can run your locations through the Mapbox Matrix API. 

- https://docs.mapbox.com/help/glossary/mapbox-matrix-api/
- https://docs.mapbox.com/api/navigation/#matrix
- https://docs.mapbox.com/android/java/overview/directions-matrix/

Sounds like you'd want to do "an asymmetric 1xN matrix" call where you get the distance from a single location to all of the various other points.

**Comment by iman100** [comment]
I want to show the nearest points with the nearest priority, from the points given.
From these links I did not notice the solution to my problem

**Comment by langsmith** [comment]
What do you mean by `nearest priority`? Does `nearest` mean actual distance or travel time? Either way, the Matrix API can deliver time or distance. The API will deliver information regarding travel from a single location to any number of other locations

<img width="626" alt="Screen Shot 2019-06-20 at 8 52 04 AM" src="https://user-images.githubusercontent.com/4394910/59862985-b2e03300-9338-11e9-8fcb-ae6cced5c43d.png">

`A –> B`, `A –> C`, `A –> D`, `A –> E`, `A –> F`, etc.

`sources=0` in your request URL is for your use case.
