### ISSUE TITLE
Issues when Removing ThemePickerActivity.java from Blog

### ISSUE THREAD

**Issue by walter-grace** [mapbox/store-locator-android#35]
I am having issues running the starter package when following this blog post from Mapbox.
I can run it without the ThemePickerActivity.java and it works, the moment I remove and add the <intent> it runs this error in the logs
_The element type "application" must be terminated by the matching end-tag "</application>"._
(https://docs.mapbox.com/help/tutorials/android-store-locator/)

**Comment by langsmith** [comment]
Hey @walter-grace . Does that app completely crash? 

> the moment I remove and add the it runs this error in the logs

What are you removing? Can you share the code at the location of the _The element type "application" must be terminated by the matching end-tag ""._ error?

**Comment by langsmith** [comment]
Closing as I haven't heard back 😕 . If I do, I'll be more than happy to keep the conversation going and re-open this.
